# metamodel_version: 1.11.0id: PreTradeComponentDetail
schema_generating: true
description: Per-category component description.
display_name: PreTradeComponentDetail
document_category: PreTradeComponentDetail
weight: 20
fields:
- id: component_name
  description: PascalCase name of the component.
  display_name: PreTradeComponentDetail_component_name
- id: repetition
  description: REPEATING or NON_REPEATING.
  display_name: repetition
- id: description
  description: Description of the component's purpose.
  display_name: PreTradeComponentDetail_description
- id: layout_url
  description: URL of the detailed message- or component-layout.
  display_name: layout_url
- id: pre_layout_rows
  description: Ordered rows of the layout table published for the message or component
    in the Pre-Trade Appendix.
  display_name: pre_layout_rows
  cardinality: multi
