// Code generated by linkml-golanggen. DO NOT EDIT.
package fixprotocol

import (
	"time"
)
// Layer of the FIX Technical Standard Stack.
type StandardLayer string

const (
	StandardLayerAPPLICATION StandardLayer = "APPLICATION"
	StandardLayerENCODING StandardLayer = "ENCODING"
	StandardLayerSESSION StandardLayer = "SESSION"
)
// Qualitative size indicator for an Extension Pack.
type ExtensionPackSize string

const (
	ExtensionPackSizeXXS ExtensionPackSize = "XXS"
	ExtensionPackSizeXS ExtensionPackSize = "XS"
	ExtensionPackSizeS ExtensionPackSize = "S"
	ExtensionPackSizeM ExtensionPackSize = "M"
	ExtensionPackSizeL ExtensionPackSize = "L"
	ExtensionPackSizeXL ExtensionPackSize = "XL"
	ExtensionPackSizeXXL ExtensionPackSize = "XXL"
)
// FIX business areas that may reference a Global Component from the FIX Latest "Global Components" page.
type GlobalComponentBusinessAreaEnum string

const (
	GlobalComponentBusinessAreaEnumPRETRADE GlobalComponentBusinessAreaEnum = "PRE_TRADE"
	GlobalComponentBusinessAreaEnumTRADE GlobalComponentBusinessAreaEnum = "TRADE"
	GlobalComponentBusinessAreaEnumPOSTTRADE GlobalComponentBusinessAreaEnum = "POST_TRADE"
	GlobalComponentBusinessAreaEnumINFRASTRUCTURE GlobalComponentBusinessAreaEnum = "INFRASTRUCTURE"
)
// Top-level business areas of the FIX Latest specification.
type BusinessAreaEnum string

const (
	BusinessAreaEnumINTRODUCTION BusinessAreaEnum = "INTRODUCTION"
	BusinessAreaEnumPRETRADE BusinessAreaEnum = "PRE_TRADE"
	BusinessAreaEnumTRADE BusinessAreaEnum = "TRADE"
	BusinessAreaEnumPOSTTRADE BusinessAreaEnum = "POST_TRADE"
	BusinessAreaEnumINFRASTRUCTURE BusinessAreaEnum = "INFRASTRUCTURE"
)
// Message categories defined within FIX Latest business areas.
type MessageCategoryEnum string

const (
	MessageCategoryEnumINDICATION MessageCategoryEnum = "INDICATION"
	MessageCategoryEnumEVENTCOMMUNICATION MessageCategoryEnum = "EVENT_COMMUNICATION"
	MessageCategoryEnumQUOTATIONNEGOTIATION MessageCategoryEnum = "QUOTATION_NEGOTIATION"
	MessageCategoryEnumMARKETDATA MessageCategoryEnum = "MARKET_DATA"
	MessageCategoryEnumMARKETSTRUCTUREREFERENCEDATA MessageCategoryEnum = "MARKET_STRUCTURE_REFERENCE_DATA"
	MessageCategoryEnumSECURITIESREFERENCEDATA MessageCategoryEnum = "SECURITIES_REFERENCE_DATA"
	MessageCategoryEnumPARTIESREFERENCEDATA MessageCategoryEnum = "PARTIES_REFERENCE_DATA"
	MessageCategoryEnumPARTIESACTION MessageCategoryEnum = "PARTIES_ACTION"
	MessageCategoryEnumSINGLEGENERALORDERHANDLING MessageCategoryEnum = "SINGLE_GENERAL_ORDER_HANDLING"
	MessageCategoryEnumORDERMASSHANDLING MessageCategoryEnum = "ORDER_MASS_HANDLING"
	MessageCategoryEnumCROSSORDERS MessageCategoryEnum = "CROSS_ORDERS"
	MessageCategoryEnumMULTILEGORDERS MessageCategoryEnum = "MULTILEG_ORDERS"
	MessageCategoryEnumLISTPROGRAMBASKETTRADING MessageCategoryEnum = "LIST_PROGRAM_BASKET_TRADING"
	MessageCategoryEnumALLOCATIONANDREADYTOBOOK MessageCategoryEnum = "ALLOCATION_AND_READY_TO_BOOK"
	MessageCategoryEnumCONFIRMATION MessageCategoryEnum = "CONFIRMATION"
	MessageCategoryEnumSETTLEMENTINSTRUCTIONS MessageCategoryEnum = "SETTLEMENT_INSTRUCTIONS"
	MessageCategoryEnumTRADECAPTUREREPORTING MessageCategoryEnum = "TRADE_CAPTURE_REPORTING"
	MessageCategoryEnumREGISTRATIONINSTRUCTIONS MessageCategoryEnum = "REGISTRATION_INSTRUCTIONS"
	MessageCategoryEnumPOSITIONSMAINTENANCE MessageCategoryEnum = "POSITIONS_MAINTENANCE"
	MessageCategoryEnumCOLLATERALMANAGEMENT MessageCategoryEnum = "COLLATERAL_MANAGEMENT"
	MessageCategoryEnumMARGINREQUIREMENTMANAGEMENT MessageCategoryEnum = "MARGIN_REQUIREMENT_MANAGEMENT"
	MessageCategoryEnumACCOUNTREPORTING MessageCategoryEnum = "ACCOUNT_REPORTING"
	MessageCategoryEnumTRADEMANAGEMENT MessageCategoryEnum = "TRADE_MANAGEMENT"
	MessageCategoryEnumPAYMANAGEMENT MessageCategoryEnum = "PAY_MANAGEMENT"
	MessageCategoryEnumSETTLEMENTSTATUSMANAGEMENT MessageCategoryEnum = "SETTLEMENT_STATUS_MANAGEMENT"
	MessageCategoryEnumBUSINESSMESSAGEREJECTS MessageCategoryEnum = "BUSINESS_MESSAGE_REJECTS"
	MessageCategoryEnumNETWORKSTATUSCOMMUNICATION MessageCategoryEnum = "NETWORK_STATUS_COMMUNICATION"
	MessageCategoryEnumUSERMANAGEMENT MessageCategoryEnum = "USER_MANAGEMENT"
	MessageCategoryEnumAPPLICATIONSEQUENCING MessageCategoryEnum = "APPLICATION_SEQUENCING"
)
// Sharing scope of a FIX component.
type ComponentScope string

const (
	ComponentScopeGLOBAL ComponentScope = "GLOBAL"
	ComponentScopeCOMMON ComponentScope = "COMMON"
	ComponentScopeSPECIFIC ComponentScope = "SPECIFIC"
)
// Thematic grouping under which a Global Component is presented.
type ComponentGroup string

const (
	ComponentGroupSECURITIES ComponentGroup = "SECURITIES"
	ComponentGroupLEGSECURITIES ComponentGroup = "LEG_SECURITIES"
	ComponentGroupUNDERLYINGSECURITIES ComponentGroup = "UNDERLYING_SECURITIES"
	ComponentGroupPARTIES ComponentGroup = "PARTIES"
	ComponentGroupORDERSANDQUOTES ComponentGroup = "ORDERS_AND_QUOTES"
	ComponentGroupTRADES ComponentGroup = "TRADES"
	ComponentGroupCOMMISSIONSANDFEES ComponentGroup = "COMMISSIONS_AND_FEES"
	ComponentGroupFINANCING ComponentGroup = "FINANCING"
	ComponentGroupPAYMENTS ComponentGroup = "PAYMENTS"
	ComponentGroupSTIPULATIONS ComponentGroup = "STIPULATIONS"
	ComponentGroupHEADERANDTRAILER ComponentGroup = "HEADER_AND_TRAILER"
	ComponentGroupMISCELLANEOUS ComponentGroup = "MISCELLANEOUS"
)
// Required-status of a field within a message or component.
type FieldRequirement string

const (
	FieldRequirementREQUIRED FieldRequirement = "REQUIRED"
	FieldRequirementOPTIONAL FieldRequirement = "OPTIONAL"
	FieldRequirementCONDITIONALLYREQUIRED FieldRequirement = "CONDITIONALLY_REQUIRED"
)
// Product/asset classes covered by FIX at the application layer.
type ProductCoverage string

const (
	ProductCoverageEQUITIES ProductCoverage = "EQUITIES"
	ProductCoverageCIV ProductCoverage = "CIV"
	ProductCoverageDERIVATIVES ProductCoverage = "DERIVATIVES"
	ProductCoverageFIXEDINCOME ProductCoverage = "FIXED_INCOME"
	ProductCoverageFOREIGNEXCHANGE ProductCoverage = "FOREIGN_EXCHANGE"
)
// Names of FIX Protocol datatypes.
type FIXDatatypeName string

const (
	FIXDatatypeNameInt FIXDatatypeName = "int"
	FIXDatatypeNameTagNum FIXDatatypeName = "TagNum"
	FIXDatatypeNameSeqNum FIXDatatypeName = "SeqNum"
	FIXDatatypeNameNumInGroup FIXDatatypeName = "NumInGroup"
	FIXDatatypeNameDayOfMonth FIXDatatypeName = "DayOfMonth"
	FIXDatatypeNameFloat FIXDatatypeName = "float"
	FIXDatatypeNameQty FIXDatatypeName = "Qty"
	FIXDatatypeNamePrice FIXDatatypeName = "Price"
	FIXDatatypeNamePriceOffset FIXDatatypeName = "PriceOffset"
	FIXDatatypeNameAmt FIXDatatypeName = "Amt"
	FIXDatatypeNamePercentage FIXDatatypeName = "Percentage"
	FIXDatatypeNameChar FIXDatatypeName = "char"
	FIXDatatypeNameBoolean FIXDatatypeName = "Boolean"
	FIXDatatypeNameString FIXDatatypeName = "String"
	FIXDatatypeNameMultipleCharValue FIXDatatypeName = "MultipleCharValue"
	FIXDatatypeNameMultipleStringValue FIXDatatypeName = "MultipleStringValue"
	FIXDatatypeNameCountry FIXDatatypeName = "Country"
	FIXDatatypeNameCurrency FIXDatatypeName = "Currency"
	FIXDatatypeNameExchange FIXDatatypeName = "Exchange"
	FIXDatatypeNameMonthYear FIXDatatypeName = "MonthYear"
	FIXDatatypeNameUTCTimestamp FIXDatatypeName = "UTCTimestamp"
	FIXDatatypeNameUTCTimeOnly FIXDatatypeName = "UTCTimeOnly"
	FIXDatatypeNameUTCDateOnly FIXDatatypeName = "UTCDateOnly"
	FIXDatatypeNameLocalMktDate FIXDatatypeName = "LocalMktDate"
	FIXDatatypeNameTZTimeOnly FIXDatatypeName = "TZTimeOnly"
	FIXDatatypeNameTZTimestamp FIXDatatypeName = "TZTimestamp"
	FIXDatatypeNameLength FIXDatatypeName = "Length"
	FIXDatatypeNameData FIXDatatypeName = "data"
	FIXDatatypeNameTenor FIXDatatypeName = "Tenor"
	FIXDatatypeNameReserved100Plus FIXDatatypeName = "Reserved100Plus"
	FIXDatatypeNameReserved1000Plus FIXDatatypeName = "Reserved1000Plus"
	FIXDatatypeNameReserved4000Plus FIXDatatypeName = "Reserved4000Plus"
	FIXDatatypeNameXMLData FIXDatatypeName = "XMLData"
	FIXDatatypeNameLanguage FIXDatatypeName = "Language"
	FIXDatatypeNameLocalMktTime FIXDatatypeName = "LocalMktTime"
)
// ISO/IEC 11404:2007 General-Purpose Datatypes value space.
type ISO11404ValueSpace string

const (
	ISO11404ValueSpaceInteger ISO11404ValueSpace = "integer"
	ISO11404ValueSpaceOrdinal ISO11404ValueSpace = "ordinal"
	ISO11404ValueSpaceSize ISO11404ValueSpace = "size"
	ISO11404ValueSpaceReal ISO11404ValueSpace = "real"
	ISO11404ValueSpaceScaled ISO11404ValueSpace = "scaled"
	ISO11404ValueSpaceCharacter ISO11404ValueSpace = "character"
	ISO11404ValueSpaceCharacterstring ISO11404ValueSpace = "characterstring"
	ISO11404ValueSpaceBoolean ISO11404ValueSpace = "boolean"
	ISO11404ValueSpaceSet ISO11404ValueSpace = "set"
	ISO11404ValueSpaceArray ISO11404ValueSpace = "array"
	ISO11404ValueSpaceTime ISO11404ValueSpace = "time"
	ISO11404ValueSpaceUnion ISO11404ValueSpace = "union"
)
// Time unit used in a FIX Tenor expression.
type TenorUnit string

const (
	TenorUnitD TenorUnit = "D"
	TenorUnitW TenorUnit = "W"
	TenorUnitM TenorUnit = "M"
	TenorUnitY TenorUnit = "Y"
)
// Named encodings of the FIX Family of Standards.
type StandardEncodingName string

const (
	StandardEncodingNameTAGVALUE StandardEncodingName = "TAGVALUE"
	StandardEncodingNameFIXML StandardEncodingName = "FIXML"
	StandardEncodingNameFAST StandardEncodingName = "FAST"
	StandardEncodingNameSBE StandardEncodingName = "SBE"
	StandardEncodingNameGPB StandardEncodingName = "GPB"
	StandardEncodingNameJSON StandardEncodingName = "JSON"
	StandardEncodingNameASN1 StandardEncodingName = "ASN_1"
)
// Named session-layer protocols in the FIX Family of Standards.
type SessionProtocolName string

const (
	SessionProtocolNameFIX42 SessionProtocolName = "FIX_4_2"
	SessionProtocolNameFIX4 SessionProtocolName = "FIX4"
	SessionProtocolNameFIXT SessionProtocolName = "FIXT"
	SessionProtocolNameLFIXT SessionProtocolName = "LFIXT"
	SessionProtocolNameFIXP SessionProtocolName = "FIXP"
	SessionProtocolNameSOFH SessionProtocolName = "SOFH"
	SessionProtocolNameFIXS SessionProtocolName = "FIXS"
	SessionProtocolNameAMQP SessionProtocolName = "AMQP"
)
// Time-unit precision for FIX time-bearing datatypes.
type TimePrecision string

const (
	TimePrecisionSECOND TimePrecision = "SECOND"
	TimePrecisionMILLISECOND TimePrecision = "MILLISECOND"
	TimePrecisionMICROSECOND TimePrecision = "MICROSECOND"
	TimePrecisionNANOSECOND TimePrecision = "NANOSECOND"
	TimePrecisionPICOSECOND TimePrecision = "PICOSECOND"
	TimePrecisionDAY TimePrecision = "DAY"
)
// Organizational bodies of FIX Protocol Limited.
type FPLCommitteeRole string

const (
	FPLCommitteeRoleGLOBALSTEERINGCOMMITTEE FPLCommitteeRole = "GLOBAL_STEERING_COMMITTEE"
	FPLCommitteeRoleGLOBALTECHNICALCOMMITTEE FPLCommitteeRole = "GLOBAL_TECHNICAL_COMMITTEE"
	FPLCommitteeRoleGLOBALPRODUCTCOMMITTEE FPLCommitteeRole = "GLOBAL_PRODUCT_COMMITTEE"
	FPLCommitteeRoleGLOBALBUYSIDECOMMITTEE FPLCommitteeRole = "GLOBAL_BUY_SIDE_COMMITTEE"
	FPLCommitteeRoleGLOBALMEMBERSERVICESCOMMITTEE FPLCommitteeRole = "GLOBAL_MEMBER_SERVICES_COMMITTEE"
	FPLCommitteeRoleREGIONALCOMMITTEE FPLCommitteeRole = "REGIONAL_COMMITTEE"
)
// Geographic regions for FPL Regional Committees.
type FPLRegion string

const (
	FPLRegionAMERICAS FPLRegion = "AMERICAS"
	FPLRegionASIAPACIFIC FPLRegion = "ASIA_PACIFIC"
	FPLRegionEMEA FPLRegion = "EMEA"
	FPLRegionJAPAN FPLRegion = "JAPAN"
)
// Global Product Committees maintained by FIX Protocol Limited.
type FPLProductGroup string

const (
	FPLProductGroupFIXEDINCOMEANDCURRENCIES FPLProductGroup = "FIXED_INCOME_AND_CURRENCIES"
	FPLProductGroupLISTEDPRODUCTSANDEXCHANGES FPLProductGroup = "LISTED_PRODUCTS_AND_EXCHANGES"
)
// Categories of organizations represented in FPL membership.
type FPLMemberType string

const (
	FPLMemberTypeBUYSIDEFIRM FPLMemberType = "BUY_SIDE_FIRM"
	FPLMemberTypeSELLSIDEFIRM FPLMemberType = "SELL_SIDE_FIRM"
	FPLMemberTypeEXCHANGE FPLMemberType = "EXCHANGE"
	FPLMemberTypeECNATS FPLMemberType = "ECN_ATS"
	FPLMemberTypeUTILITY FPLMemberType = "UTILITY"
	FPLMemberTypeVENDOR FPLMemberType = "VENDOR"
	FPLMemberTypeOTHERASSOCIATION FPLMemberType = "OTHER_ASSOCIATION"
)
// Usage policy assigned to a reserved range of UDF tag numbers.
type UDFTagRangeUsage string

const (
	UDFTagRangeUsageINTERFIRMREGISTERED UDFTagRangeUsage = "INTER_FIRM_REGISTERED"
	UDFTagRangeUsageINTERFIRMBILATERAL UDFTagRangeUsage = "INTER_FIRM_BILATERAL"
	UDFTagRangeUsageGTCREGULATORYLEGACY UDFTagRangeUsage = "GTC_REGULATORY_LEGACY"
	UDFTagRangeUsageWIPCHINA UDFTagRangeUsage = "WIP_CHINA"
	UDFTagRangeUsageINTERNALFIRM UDFTagRangeUsage = "INTERNAL_FIRM"
	UDFTagRangeUsageGTCOTCDERIVATIVES UDFTagRangeUsage = "GTC_OTC_DERIVATIVES"
	UDFTagRangeUsageGTCRESERVED UDFTagRangeUsage = "GTC_RESERVED"
)
// The eight message categories of the FIX Latest Pre-Trade business area. Subset of MessageCategoryEnum.
type PreTradeCategoryEnum string

const (
	PreTradeCategoryEnumINDICATION PreTradeCategoryEnum = "INDICATION"
	PreTradeCategoryEnumEVENTCOMMUNICATION PreTradeCategoryEnum = "EVENT_COMMUNICATION"
	PreTradeCategoryEnumQUOTATIONNEGOTIATION PreTradeCategoryEnum = "QUOTATION_NEGOTIATION"
	PreTradeCategoryEnumMARKETDATA PreTradeCategoryEnum = "MARKET_DATA"
	PreTradeCategoryEnumMARKETSTRUCTUREREFERENCEDATA PreTradeCategoryEnum = "MARKET_STRUCTURE_REFERENCE_DATA"
	PreTradeCategoryEnumSECURITIESREFERENCEDATA PreTradeCategoryEnum = "SECURITIES_REFERENCE_DATA"
	PreTradeCategoryEnumPARTIESREFERENCEDATA PreTradeCategoryEnum = "PARTIES_REFERENCE_DATA"
	PreTradeCategoryEnumPARTIESACTION PreTradeCategoryEnum = "PARTIES_ACTION"
)
// Whether a FIX component is repeating or non-repeating.
type ComponentRepetition string

const (
	ComponentRepetitionREPEATING ComponentRepetition = "REPEATING"
	ComponentRepetitionNONREPEATING ComponentRepetition = "NON_REPEATING"
)
// Names of the Common Components declared at the top of the Pre-Trade business-area chapter.
type PreTradeCommonComponentName string

const (
	PreTradeCommonComponentNameAuctionTypeRuleGrp PreTradeCommonComponentName = "AuctionTypeRuleGrp"
	PreTradeCommonComponentNameBaseTradingRules PreTradeCommonComponentName = "BaseTradingRules"
	PreTradeCommonComponentNameExecInstRules PreTradeCommonComponentName = "ExecInstRules"
	PreTradeCommonComponentNameInstrumentScope PreTradeCommonComponentName = "InstrumentScope"
	PreTradeCommonComponentNameInstrumentScopeGrp PreTradeCommonComponentName = "InstrumentScopeGrp"
	PreTradeCommonComponentNameInstrumentScopeSecurityAltIDGrp PreTradeCommonComponentName = "InstrumentScopeSecurityAltIDGrp"
	PreTradeCommonComponentNameLotTypeRules PreTradeCommonComponentName = "LotTypeRules"
	PreTradeCommonComponentNameMarketDataFeedTypes PreTradeCommonComponentName = "MarketDataFeedTypes"
	PreTradeCommonComponentNameMarketSegmentScopeGrp PreTradeCommonComponentName = "MarketSegmentScopeGrp"
	PreTradeCommonComponentNameMatchRules PreTradeCommonComponentName = "MatchRules"
	PreTradeCommonComponentNameOrdTypeRules PreTradeCommonComponentName = "OrdTypeRules"
	PreTradeCommonComponentNamePriceLimits PreTradeCommonComponentName = "PriceLimits"
	PreTradeCommonComponentNamePriceRangeRuleGrp PreTradeCommonComponentName = "PriceRangeRuleGrp"
	PreTradeCommonComponentNameQuoteSizeRuleGrp PreTradeCommonComponentName = "QuoteSizeRuleGrp"
	PreTradeCommonComponentNameRequestedPartyRoleGrp PreTradeCommonComponentName = "RequestedPartyRoleGrp"
	PreTradeCommonComponentNameRequestingPartyGrp PreTradeCommonComponentName = "RequestingPartyGrp"
	PreTradeCommonComponentNameRequestingPartySubGrp PreTradeCommonComponentName = "RequestingPartySubGrp"
	PreTradeCommonComponentNameRoutingGrp PreTradeCommonComponentName = "RoutingGrp"
	PreTradeCommonComponentNameTickRules PreTradeCommonComponentName = "TickRules"
	PreTradeCommonComponentNameTimeInForceRules PreTradeCommonComponentName = "TimeInForceRules"
	PreTradeCommonComponentNameTradingSessionRules PreTradeCommonComponentName = "TradingSessionRules"
)
// Quoting business models referenced in the Quotation / Negotiation category.
type QuoteModelEnum string

const (
	QuoteModelEnumINDICATIVE QuoteModelEnum = "INDICATIVE"
	QuoteModelEnumTRADEABLE QuoteModelEnum = "TRADEABLE"
	QuoteModelEnumRESTRICTEDTRADEABLE QuoteModelEnum = "RESTRICTED_TRADEABLE"
	QuoteModelEnumNEGOTIATION QuoteModelEnum = "NEGOTIATION"
)
// Discriminator for a row in a Pre-Trade message- or component-layout table: either a FIX field (numeric Tag column) or an embedded component (literal "Component" in the Tag column).
type PreTradeLayoutRowKindEnum string

const (
	PreTradeLayoutRowKindEnumFIELD PreTradeLayoutRowKindEnum = "FIELD"
	PreTradeLayoutRowKindEnumCOMPONENT PreTradeLayoutRowKindEnum = "COMPONENT"
)
// The five message categories of the FIX Latest Trade (Orders and Executions) business area. Subset of MessageCategoryEnum.
type TradeCategoryEnum string

const (
	TradeCategoryEnumSINGLEGENERALORDERHANDLING TradeCategoryEnum = "SINGLE_GENERAL_ORDER_HANDLING"
	TradeCategoryEnumORDERMASSHANDLING TradeCategoryEnum = "ORDER_MASS_HANDLING"
	TradeCategoryEnumCROSSORDERHANDLING TradeCategoryEnum = "CROSS_ORDER_HANDLING"
	TradeCategoryEnumMULTILEGORDERHANDLING TradeCategoryEnum = "MULTILEG_ORDER_HANDLING"
	TradeCategoryEnumLISTPROGRAMBASKETTRADING TradeCategoryEnum = "LIST_PROGRAM_BASKET_TRADING"
)
// Whether a FIX component is repeating or non-repeating.
type TradeComponentRepetition string

const (
	TradeComponentRepetitionREPEATING TradeComponentRepetition = "REPEATING"
	TradeComponentRepetitionNONREPEATING TradeComponentRepetition = "NON_REPEATING"
)
// Names of the Common Components declared at the bottom of the Trade business-area chapter — components used by messages across more than one Trade category.
type TradeCommonComponentName string

const (
	TradeCommonComponentNameDisclosureInstructionGrp TradeCommonComponentName = "DisclosureInstructionGrp"
	TradeCommonComponentNameDiscretionInstructions TradeCommonComponentName = "DiscretionInstructions"
	TradeCommonComponentNamePegInstructions TradeCommonComponentName = "PegInstructions"
	TradeCommonComponentNamePreAllocGrp TradeCommonComponentName = "PreAllocGrp"
	TradeCommonComponentNameStrategyParametersGrp TradeCommonComponentName = "StrategyParametersGrp"
	TradeCommonComponentNameTriggeringInstruction TradeCommonComponentName = "TriggeringInstruction"
)
// Discriminator for a row in a Trade message- or component-layout table: either a FIX field (numeric Tag column) or an embedded component (literal "Component" in the Tag column).
type TradeLayoutRowKindEnum string

const (
	TradeLayoutRowKindEnumFIELD TradeLayoutRowKindEnum = "FIELD"
	TradeLayoutRowKindEnumCOMPONENT TradeLayoutRowKindEnum = "COMPONENT"
)
// The twelve message categories of the FIX Latest Post-Trade business area. Subset of MessageCategoryEnum.
type PostTradeCategoryEnum string

const (
	PostTradeCategoryEnumALLOCATION PostTradeCategoryEnum = "ALLOCATION"
	PostTradeCategoryEnumCONFIRMATION PostTradeCategoryEnum = "CONFIRMATION"
	PostTradeCategoryEnumSETTLEMENTINSTRUCTION PostTradeCategoryEnum = "SETTLEMENT_INSTRUCTION"
	PostTradeCategoryEnumTRADECAPTUREREPORTING PostTradeCategoryEnum = "TRADE_CAPTURE_REPORTING"
	PostTradeCategoryEnumREGISTRATIONINSTRUCTION PostTradeCategoryEnum = "REGISTRATION_INSTRUCTION"
	PostTradeCategoryEnumPOSITIONMAINTENANCE PostTradeCategoryEnum = "POSITION_MAINTENANCE"
	PostTradeCategoryEnumCOLLATERALMANAGEMENT PostTradeCategoryEnum = "COLLATERAL_MANAGEMENT"
	PostTradeCategoryEnumMARGINREQUIREMENTMANAGEMENT PostTradeCategoryEnum = "MARGIN_REQUIREMENT_MANAGEMENT"
	PostTradeCategoryEnumACCOUNTREPORTING PostTradeCategoryEnum = "ACCOUNT_REPORTING"
	PostTradeCategoryEnumTRADEMANAGEMENT PostTradeCategoryEnum = "TRADE_MANAGEMENT"
	PostTradeCategoryEnumPAYMANAGEMENT PostTradeCategoryEnum = "PAY_MANAGEMENT"
	PostTradeCategoryEnumSETTLEMENTSTATUSMANAGEMENT PostTradeCategoryEnum = "SETTLEMENT_STATUS_MANAGEMENT"
)
// Names of the Common Components declared at the top of the Post-Trade business-area chapter.
type PostTradeCommonComponentName string

const (
	PostTradeCommonComponentNameAllocCommissionDataGrp PostTradeCommonComponentName = "AllocCommissionDataGrp"
	PostTradeCommonComponentNameAllocRegulatoryTradeIDGrp PostTradeCommonComponentName = "AllocRegulatoryTradeIDGrp"
	PostTradeCommonComponentNameClrInstGrp PostTradeCommonComponentName = "ClrInstGrp"
	PostTradeCommonComponentNameCollateralAmountGrp PostTradeCommonComponentName = "CollateralAmountGrp"
	PostTradeCommonComponentNameCollateralReinvestmentGrp PostTradeCommonComponentName = "CollateralReinvestmentGrp"
	PostTradeCommonComponentNameDlvyInstGrp PostTradeCommonComponentName = "DlvyInstGrp"
	PostTradeCommonComponentNameExecAllocGrp PostTradeCommonComponentName = "ExecAllocGrp"
	PostTradeCommonComponentNameMarginAmount PostTradeCommonComponentName = "MarginAmount"
	PostTradeCommonComponentNameOrdAllocGrp PostTradeCommonComponentName = "OrdAllocGrp"
	PostTradeCommonComponentNamePositionAmountData PostTradeCommonComponentName = "PositionAmountData"
	PostTradeCommonComponentNameSettlDetails PostTradeCommonComponentName = "SettlDetails"
	PostTradeCommonComponentNameSettlInstructionsData PostTradeCommonComponentName = "SettlInstructionsData"
	PostTradeCommonComponentNameSettlParties PostTradeCommonComponentName = "SettlParties"
	PostTradeCommonComponentNameSettlPtysSubGrp PostTradeCommonComponentName = "SettlPtysSubGrp"
	PostTradeCommonComponentNameTradeAllocAmtGrp PostTradeCommonComponentName = "TradeAllocAmtGrp"
	PostTradeCommonComponentNameTransactionAttributeGrp PostTradeCommonComponentName = "TransactionAttributeGrp"
)
// Communication options by which an Initiator may convey allocation instructions to a Respondent.
type AllocationScenarioEnum string

const (
	AllocationScenarioEnumPREALLOCATEDORDER AllocationScenarioEnum = "PRE_ALLOCATED_ORDER"
	AllocationScenarioEnumPRETRADEALLOCATION AllocationScenarioEnum = "PRE_TRADE_ALLOCATION"
	AllocationScenarioEnumPOSTTRADEALLOCATION AllocationScenarioEnum = "POST_TRADE_ALLOCATION"
	AllocationScenarioEnumREADYTOBOOK AllocationScenarioEnum = "READY_TO_BOOK"
)
// AllocStatus(87) values used in allocation acknowledgement messages.
type AllocationStatusEnum string

const (
	AllocationStatusEnumACCEPTED AllocationStatusEnum = "ACCEPTED"
	AllocationStatusEnumBLOCKLEVELREJECT AllocationStatusEnum = "BLOCK_LEVEL_REJECT"
	AllocationStatusEnumACCOUNTLEVELREJECT AllocationStatusEnum = "ACCOUNT_LEVEL_REJECT"
	AllocationStatusEnumRECEIVEDNOTYETPROCESSED AllocationStatusEnum = "RECEIVED_NOT_YET_PROCESSED"
)
// AllocTransType(71) values.
type AllocationTransactionTypeEnum string

const (
	AllocationTransactionTypeEnumNEW AllocationTransactionTypeEnum = "NEW"
	AllocationTransactionTypeEnumREPLACE AllocationTransactionTypeEnum = "REPLACE"
	AllocationTransactionTypeEnumCANCEL AllocationTransactionTypeEnum = "CANCEL"
)
// Methods by which post-trade allocations may be computed.
type PostTradeAllocationPricingMethodEnum string

const (
	PostTradeAllocationPricingMethodEnumAVERAGEPRICE PostTradeAllocationPricingMethodEnum = "AVERAGE_PRICE"
	PostTradeAllocationPricingMethodEnumEXECUTEDPRICE PostTradeAllocationPricingMethodEnum = "EXECUTED_PRICE"
)
// Direction of a TradeCaptureReport relative to the marketplace.
type TradeCaptureReportDirectionEnum string

const (
	TradeCaptureReportDirectionEnumINBOUND TradeCaptureReportDirectionEnum = "INBOUND"
	TradeCaptureReportDirectionEnumOUTBOUND TradeCaptureReportDirectionEnum = "OUTBOUND"
)
// Documented usages of the TradeCaptureReport(35=AE) message.
type TradeCaptureReportUsageEnum string

const (
	TradeCaptureReportUsageEnumRELAYCONFIRMEDTRADESTONONPARTICIPANTS TradeCaptureReportUsageEnum = "RELAY_CONFIRMED_TRADES_TO_NON_PARTICIPANTS"
	TradeCaptureReportUsageEnumRELAYCONFIRMEDTRADESTOCOUNTERPARTIES TradeCaptureReportUsageEnum = "RELAY_CONFIRMED_TRADES_TO_COUNTERPARTIES"
	TradeCaptureReportUsageEnumREPORTINGPRIVATELYNEGOTIATEDTRADES TradeCaptureReportUsageEnum = "REPORTING_PRIVATELY_NEGOTIATED_TRADES"
	TradeCaptureReportUsageEnumREPORTINGFLOORORROUTEDEXECUTIONS TradeCaptureReportUsageEnum = "REPORTING_FLOOR_OR_ROUTED_EXECUTIONS"
	TradeCaptureReportUsageEnumREQUESTTRADECANCELORAMENDMENT TradeCaptureReportUsageEnum = "REQUEST_TRADE_CANCEL_OR_AMENDMENT"
)
// Roles played by trade-capture-report identifier fields.
type TradeCaptureReportIdentifierRoleEnum string

const (
	TradeCaptureReportIdentifierRoleEnumTRADEREPORTID TradeCaptureReportIdentifierRoleEnum = "TRADE_REPORT_ID"
	TradeCaptureReportIdentifierRoleEnumTRADEID TradeCaptureReportIdentifierRoleEnum = "TRADE_ID"
	TradeCaptureReportIdentifierRoleEnumTRADEREPORTREFID TradeCaptureReportIdentifierRoleEnum = "TRADE_REPORT_REF_ID"
	TradeCaptureReportIdentifierRoleEnumSECONDARYTRADEID TradeCaptureReportIdentifierRoleEnum = "SECONDARY_TRADE_ID"
)
// RegistTransType(514) values.
type RegistrationTransactionTypeEnum string

const (
	RegistrationTransactionTypeEnumNEW RegistrationTransactionTypeEnum = "NEW"
	RegistrationTransactionTypeEnumREPLACE RegistrationTransactionTypeEnum = "REPLACE"
	RegistrationTransactionTypeEnumCANCEL RegistrationTransactionTypeEnum = "CANCEL"
)
// RegistStatus(506) values.
type RegistrationStatusEnum string

const (
	RegistrationStatusEnumACCEPTED RegistrationStatusEnum = "ACCEPTED"
	RegistrationStatusEnumREJECTED RegistrationStatusEnum = "REJECTED"
	RegistrationStatusEnumHELD RegistrationStatusEnum = "HELD"
	RegistrationStatusEnumREMINDER RegistrationStatusEnum = "REMINDER"
)
// SettlInstMode(160) values relevant in Post-Trade.
type SettlementInstructionModeEnum string

const (
	SettlementInstructionModeEnumSTANDINGINSTRUCTIONS SettlementInstructionModeEnum = "STANDING_INSTRUCTIONS"
	SettlementInstructionModeEnumSPECIFICORDER SettlementInstructionModeEnum = "SPECIFIC_ORDER"
	SettlementInstructionModeEnumREQUESTREJECT SettlementInstructionModeEnum = "REQUEST_REJECT"
)
// SettlObligMode(1159) values.
type SettlementObligationModeEnum string

const (
	SettlementObligationModeEnumPRELIMINARY SettlementObligationModeEnum = "PRELIMINARY"
	SettlementObligationModeEnumFINAL SettlementObligationModeEnum = "FINAL"
)
// PosMaintAction(712) values.
type PositionMaintenanceActionEnum string

const (
	PositionMaintenanceActionEnumNEW PositionMaintenanceActionEnum = "NEW"
	PositionMaintenanceActionEnumREPLACE PositionMaintenanceActionEnum = "REPLACE"
	PositionMaintenanceActionEnumCANCEL PositionMaintenanceActionEnum = "CANCEL"
	PositionMaintenanceActionEnumREVERSE PositionMaintenanceActionEnum = "REVERSE"
)
// Business functions invokable via the Position Management Clearing Services.
type ClearingServiceForPositionManagementEnum string

const (
	ClearingServiceForPositionManagementEnumPOSITIONCHANGESUBMISSION ClearingServiceForPositionManagementEnum = "POSITION_CHANGE_SUBMISSION"
	ClearingServiceForPositionManagementEnumPOSITIONADJUSTMENT ClearingServiceForPositionManagementEnum = "POSITION_ADJUSTMENT"
	ClearingServiceForPositionManagementEnumEXERCISENOTICE ClearingServiceForPositionManagementEnum = "EXERCISE_NOTICE"
	ClearingServiceForPositionManagementEnumABANDONMENTNOTICE ClearingServiceForPositionManagementEnum = "ABANDONMENT_NOTICE"
	ClearingServiceForPositionManagementEnumMARGINDISPOSITION ClearingServiceForPositionManagementEnum = "MARGIN_DISPOSITION"
	ClearingServiceForPositionManagementEnumPOSITIONPLEDGE ClearingServiceForPositionManagementEnum = "POSITION_PLEDGE"
	ClearingServiceForPositionManagementEnumREQUESTFORPOSITION ClearingServiceForPositionManagementEnum = "REQUEST_FOR_POSITION"
)
// Message-format families used by the Post-Trade Processing Clearing Services.
type ClearingServiceForPostTradeProcessingEnum string

const (
	ClearingServiceForPostTradeProcessingEnumETP ClearingServiceForPostTradeProcessingEnum = "ETP"
	ClearingServiceForPostTradeProcessingEnumGIVEUP ClearingServiceForPostTradeProcessingEnum = "GIVE_UP"
	ClearingServiceForPostTradeProcessingEnumEXCHANGEFORPHYSICAL ClearingServiceForPostTradeProcessingEnum = "EXCHANGE_FOR_PHYSICAL"
	ClearingServiceForPostTradeProcessingEnumAVERAGEPRICESYSTEM ClearingServiceForPostTradeProcessingEnum = "AVERAGE_PRICE_SYSTEM"
	ClearingServiceForPostTradeProcessingEnumMUTUALOFFSETSYSTEM ClearingServiceForPostTradeProcessingEnum = "MUTUAL_OFFSET_SYSTEM"
	ClearingServiceForPostTradeProcessingEnumTRADEENTRYEDIT ClearingServiceForPostTradeProcessingEnum = "TRADE_ENTRY_EDIT"
)
// Documented uses of the Collateral Management messages.
type CollateralManagementUsageEnum string

const (
	CollateralManagementUsageEnumSECURITIESFINANCINGCOLLATERALIZATION CollateralManagementUsageEnum = "SECURITIES_FINANCING_COLLATERALIZATION"
	CollateralManagementUsageEnumCLEARINGHOUSECOLLATERALIZATION CollateralManagementUsageEnum = "CLEARING_HOUSE_COLLATERALIZATION"
)
// Purposes for which a CollateralAssignment may be sent.
type CollateralAssignmentPurposeEnum string

const (
	CollateralAssignmentPurposeEnumASSIGNINITIALCOLLATERAL CollateralAssignmentPurposeEnum = "ASSIGN_INITIAL_COLLATERAL"
	CollateralAssignmentPurposeEnumREPLENISHCOLLATERAL CollateralAssignmentPurposeEnum = "REPLENISH_COLLATERAL"
	CollateralAssignmentPurposeEnumREPLACEORSUBSTITUTECOLLATERAL CollateralAssignmentPurposeEnum = "REPLACE_OR_SUBSTITUTE_COLLATERAL"
)
// Role labels used throughout the Allocation category prose to designate the sender and receiver of an AllocationInstruction.
type AllocationRoleEnum string

const (
	AllocationRoleEnumINITIATOR AllocationRoleEnum = "INITIATOR"
	AllocationRoleEnumRESPONDENT AllocationRoleEnum = "RESPONDENT"
)
// MatchStatus(573) values referenced in Post-Trade prose.
type MatchStatusEnum string

const (
	MatchStatusEnumCOMPAREDMATCHEDORAFFIRMED MatchStatusEnum = "COMPARED_MATCHED_OR_AFFIRMED"
	MatchStatusEnumUNCOMPAREDUNMATCHEDORUNAFFIRMED MatchStatusEnum = "UNCOMPARED_UNMATCHED_OR_UNAFFIRMED"
)
// Discriminator for a row in a Post-Trade message- or component-layout table: either a FIX field (numeric Tag column) or an embedded component (literal "Component" in the Tag column).
type PostTradeLayoutRowKindEnum string

const (
	PostTradeLayoutRowKindEnumFIELD PostTradeLayoutRowKindEnum = "FIELD"
	PostTradeLayoutRowKindEnumCOMPONENT PostTradeLayoutRowKindEnum = "COMPONENT"
)
// The four message categories of the FIX Latest Infrastructure business area. Subset of MessageCategoryEnum.
type InfrastructureCategoryEnum string

const (
	InfrastructureCategoryEnumBUSINESSMESSAGEREJECTS InfrastructureCategoryEnum = "BUSINESS_MESSAGE_REJECTS"
	InfrastructureCategoryEnumNETWORKSTATUSCOMMUNICATION InfrastructureCategoryEnum = "NETWORK_STATUS_COMMUNICATION"
	InfrastructureCategoryEnumUSERMANAGEMENT InfrastructureCategoryEnum = "USER_MANAGEMENT"
	InfrastructureCategoryEnumAPPLICATIONSEQUENCING InfrastructureCategoryEnum = "APPLICATION_SEQUENCING"
)
// Names of the components defined in the Infrastructure business-area chapter. None of these are shared across categories within the area; footnotes 1–4 record that four of them were historically declared as common components.
type InfrastructureComponentName string

const (
	InfrastructureComponentNameApplIDReportGrp InfrastructureComponentName = "ApplIDReportGrp"
	InfrastructureComponentNameApplIDRequestAckGrp InfrastructureComponentName = "ApplIDRequestAckGrp"
	InfrastructureComponentNameApplIDRequestGrp InfrastructureComponentName = "ApplIDRequestGrp"
	InfrastructureComponentNameCompIDReqGrp InfrastructureComponentName = "CompIDReqGrp"
	InfrastructureComponentNameCompIDStatGrp InfrastructureComponentName = "CompIDStatGrp"
	InfrastructureComponentNameThrottleMsgTypeGrp InfrastructureComponentName = "ThrottleMsgTypeGrp"
	InfrastructureComponentNameThrottleParamsGrp InfrastructureComponentName = "ThrottleParamsGrp"
	InfrastructureComponentNameUsernameGrp InfrastructureComponentName = "UsernameGrp"
)
// Permissible values of BusinessRejectReason(380) on the BusinessMessageReject(35=j) message.
type BusinessRejectReasonEnum string

const (
	BusinessRejectReasonEnumOTHER BusinessRejectReasonEnum = "OTHER"
	BusinessRejectReasonEnumUNKNOWNID BusinessRejectReasonEnum = "UNKNOWN_ID"
	BusinessRejectReasonEnumUNKNOWNSECURITY BusinessRejectReasonEnum = "UNKNOWN_SECURITY"
	BusinessRejectReasonEnumUNSUPPORTEDMESSAGETYPE BusinessRejectReasonEnum = "UNSUPPORTED_MESSAGE_TYPE"
	BusinessRejectReasonEnumAPPLICATIONNOTAVAILABLE BusinessRejectReasonEnum = "APPLICATION_NOT_AVAILABLE"
	BusinessRejectReasonEnumCONDITIONALLYREQUIREDFIELDMISSING BusinessRejectReasonEnum = "CONDITIONALLY_REQUIRED_FIELD_MISSING"
	BusinessRejectReasonEnumNOTAUTHORISED BusinessRejectReasonEnum = "NOT_AUTHORISED"
	BusinessRejectReasonEnumDELIVERTOFIRMNOTAVAILABLE BusinessRejectReasonEnum = "DELIVER_TO_FIRM_NOT_AVAILABLE"
	BusinessRejectReasonEnumTHROTTLELIMITEXCEEDED BusinessRejectReasonEnum = "THROTTLE_LIMIT_EXCEEDED"
	BusinessRejectReasonEnumTHROTTLELIMITEXCEEDEDSESSIONDISCONNECT BusinessRejectReasonEnum = "THROTTLE_LIMIT_EXCEEDED_SESSION_DISCONNECT"
	BusinessRejectReasonEnumTHROTTLEDMESSAGESREJECTEDONREQUEST BusinessRejectReasonEnum = "THROTTLED_MESSAGES_REJECTED_ON_REQUEST"
	BusinessRejectReasonEnumINVALIDPRICEINCREMENT BusinessRejectReasonEnum = "INVALID_PRICE_INCREMENT"
)
// Network Status Communication usage scenarios documented in the chapter (Scenario A: hub-and-spoke; Scenario B: global brokerage region availability).
type NetworkStatusScenarioEnum string

const (
	NetworkStatusScenarioEnumSCENARIOA NetworkStatusScenarioEnum = "SCENARIO_A"
	NetworkStatusScenarioEnumSCENARIOB NetworkStatusScenarioEnum = "SCENARIO_B"
)
// Documented uses of ApplicationMessageReport(35=BY) selected via ApplReportType(1426).
type ApplicationMessageReportTypeEnum string

const (
	ApplicationMessageReportTypeEnumRESET ApplicationMessageReportTypeEnum = "RESET"
	ApplicationMessageReportTypeEnumLASTMESSAGE ApplicationMessageReportTypeEnum = "LAST_MESSAGE"
	ApplicationMessageReportTypeEnumKEEPALIVE ApplicationMessageReportTypeEnum = "KEEP_ALIVE"
	ApplicationMessageReportTypeEnumRESENDCOMPLETED ApplicationMessageReportTypeEnum = "RESEND_COMPLETED"
)
// Values of NetworkRequestType(935) explicitly cited in the NetworkCounterpartySystemStatusRequest(35=BC) prose.
type NetworkRequestTypeEnum string

const (
	NetworkRequestTypeEnumSNAPSHOT NetworkRequestTypeEnum = "SNAPSHOT"
	NetworkRequestTypeEnumSTOPSUBSCRIBING NetworkRequestTypeEnum = "STOP_SUBSCRIBING"
)
// Direction of a "Standard Response" mapping — which area the requesting message belongs to.
type StandardResponseDirectionEnum string

const (
	StandardResponseDirectionEnumPRETRADE StandardResponseDirectionEnum = "PRE_TRADE"
	StandardResponseDirectionEnumTRADE StandardResponseDirectionEnum = "TRADE"
	StandardResponseDirectionEnumPOSTTRADE StandardResponseDirectionEnum = "POST_TRADE"
)
// Direction of an "application message reference" key-field mapping — which area the referenced message belongs to.
type BusinessMessageReferenceDirectionEnum string

const (
	BusinessMessageReferenceDirectionEnumPRETRADE BusinessMessageReferenceDirectionEnum = "PRE_TRADE"
	BusinessMessageReferenceDirectionEnumTRADE BusinessMessageReferenceDirectionEnum = "TRADE"
	BusinessMessageReferenceDirectionEnumPOSTTRADE BusinessMessageReferenceDirectionEnum = "POST_TRADE"
)
// Names of the Global Components (declared in the FIX Latest "Global Components" page) that the Infrastructure business-area messages explicitly reference. Global Components are reusable component blocks used across two or more business areas.
type InfrastructureGlobalComponentName string

const (
	InfrastructureGlobalComponentNameApplicationSequenceControl InfrastructureGlobalComponentName = "ApplicationSequenceControl"
)
// Tags contributed by the ApplicationSequenceControl global component (used by Application Sequencing messages and by all FIX messages representing reports).
type ApplicationSequenceControlFieldName string

const (
	ApplicationSequenceControlFieldNameApplID ApplicationSequenceControlFieldName = "ApplID"
	ApplicationSequenceControlFieldNameApplSeqNum ApplicationSequenceControlFieldName = "ApplSeqNum"
	ApplicationSequenceControlFieldNameApplLastSeqNum ApplicationSequenceControlFieldName = "ApplLastSeqNum"
	ApplicationSequenceControlFieldNameApplResendFlag ApplicationSequenceControlFieldName = "ApplResendFlag"
)
// Discriminator for a row in an Infrastructure message- or component-layout table: either a FIX field (numeric Tag column) or an embedded component (literal "Component" in the Tag column).
type InfrastructureLayoutRowKindEnum string

const (
	InfrastructureLayoutRowKindEnumFIELD InfrastructureLayoutRowKindEnum = "FIELD"
	InfrastructureLayoutRowKindEnumCOMPONENT InfrastructureLayoutRowKindEnum = "COMPONENT"
)
// Container for the structural elements of the FIX Latest Introduction section. Tree root for instance data.
type FIXIntroduction struct {
	// Version stamp from the document header.
	PublishedVersion *string `json:"published_version,omitempty"`
	// Publication date of the document.
	PublishedDate *time.Time `json:"published_date,omitempty"`
	// Publishing body of the FIX Latest specification.
	Publisher *string `json:"publisher,omitempty"`
	// The Preface text of the specification.
	Preface *string `json:"preface,omitempty"`
	// The Introduction prose section.
	IntroductionText *string `json:"introduction_text,omitempty"`
	// Prose note on UTC leap-second handling for UTCTimestamp.
	UtcLeapSecondsNote *string `json:"utc_leap_seconds_note,omitempty"`
	// Information about FIX Protocol Limited.
	AboutFpl *FIXProtocolLimited `json:"about_fpl,omitempty"`
	// The FIX Family of Standards.
	Standards []FIXFamilyStandard `json:"standards,omitempty"`
	// The list of Extension Packs.
	ExtensionPacks []ExtensionPack `json:"extension_packs,omitempty"`
	// FIX Protocol datatype definitions and value spaces.
	Datatypes []FIXDatatype `json:"datatypes,omitempty"`
	// Top-level business areas of FIX Latest.
	BusinessAreas []BusinessArea `json:"business_areas,omitempty"`
	// Global Components defined in the Introduction.
	GlobalComponents []GlobalComponent `json:"global_components,omitempty"`
	// Reserved ranges of user-defined-field tag numbers.
	UdfRanges []UDFTagRange `json:"udf_ranges,omitempty"`
	// Product/asset classes covered by FIX at the application layer.
	ProductCoverage []ProductCoverage `json:"product_coverage,omitempty"`
}

// The organization that maintains the FIX Protocol specification.
type FIXProtocolLimited struct {
	// Brand name used by the organization.
	BrandName *string `json:"brand_name,omitempty"`
	// Legal name of the organization.
	LegalName *string `json:"legal_name,omitempty"`
	// Main website URL of the organization.
	Website *string `json:"website,omitempty"`
	// URL listing current FPL Member firms.
	MemberFirmsUrl *string `json:"member_firms_url,omitempty"`
	// URL listing currently active FPL Working Groups.
	WorkingGroupsUrl *string `json:"working_groups_url,omitempty"`
	// URL listing Product and Regional Committees.
	CommitteesUrl *string `json:"committees_url,omitempty"`
	// Organization categories represented in FPL membership.
	MemberTypes []FPLMemberType `json:"member_types,omitempty"`
	// High-level governance bodies that represent FPL.
	GovernanceBodies []FPLCommitteeRole `json:"governance_bodies,omitempty"`
	// Global Product Committees maintained by FPL.
	ProductCommittees []FPLProductGroup `json:"product_committees,omitempty"`
	// Regional Committees maintained by FPL.
	RegionalCommittees []FPLRegion `json:"regional_committees,omitempty"`
}

// A member standard of the FIX Family of Standards.
type FIXFamilyStandard struct {
	// Unique identifier (CURIE or local name) of the element.
	Id string `json:"id"`
	// Display name of the element.
	Name string `json:"name"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Short acronym used to refer to the standard.
	Acronym *string `json:"acronym,omitempty"`
	// Related external resources.
	SeeAlso []string `json:"see_also,omitempty"`
	// The layer the standard belongs to.
	Layer StandardLayer `json:"layer"`
	// Version of the standard, if applicable.
	Version *string `json:"version,omitempty"`
	// Name of the session profile for session-layer variants.
	SessionProfile SessionProtocolName `json:"session_profile,omitempty"`
	// Named encoding, when layer is ENCODING.
	EncodingName StandardEncodingName `json:"encoding_name,omitempty"`
}

// A unit of change to FIX Latest.
type ExtensionPack struct {
	// Sequential identifier of the Extension Pack.
	Number int `json:"number"`
	// Short descriptive title.
	Title string `json:"title"`
	// Qualitative size indicator (XXS..XXL).
	Size ExtensionPackSize `json:"size,omitempty"`
	// Narrative summary of what the EP introduces.
	EnhancementSummary *string `json:"enhancement_summary,omitempty"`
	// True when the EP applies only to the FIX Session Layer.
	AppliesToSessionLayerOnly *bool `json:"applies_to_session_layer_only,omitempty"`
	// True when the EP applies only to the FIXML encoding.
	AppliesToFixmlOnly *bool `json:"applies_to_fixml_only,omitempty"`
}

// A FIX Protocol datatype.
type FIXDatatype struct {
	// Canonical FIX datatype name.
	DatatypeName FIXDatatypeName `json:"datatype_name"`
	// Prose definition of the datatype.
	Definition string `json:"definition"`
	// ISO/IEC 11404:2007 GPD value space assigned to the datatype.
	ValueSpace []ISO11404ValueSpace `json:"value_space,omitempty"`
	// Additional value-space constraints.
	ValueSpaceNotes *string `json:"value_space_notes,omitempty"`
	// True for datatypes not permitted in new designs.
	DeprecatedForNewDesigns *bool `json:"deprecated_for_new_designs,omitempty"`
	// Reference standard for datatypes backed by an external code set.
	ExternalCodeSet *string `json:"external_code_set,omitempty"`
	// Time-unit precision for time-bearing datatypes.
	TimeUnit []TimePrecision `json:"time_unit,omitempty"`
	// Numeric radix for scaled value-space datatypes.
	Radix *int `json:"radix,omitempty"`
	// Character repertoire for character/string datatypes.
	Repertoire *string `json:"repertoire,omitempty"`
	// Inclusive lower bound of a bounded-array index.
	IndexLowerBound *int `json:"index_lower_bound,omitempty"`
	// Inclusive upper bound of a bounded-array index.
	IndexUpperBound *int `json:"index_upper_bound,omitempty"`
	// Inclusive lower bound on the integer value space.
	MinimumValue *int `json:"minimum_value,omitempty"`
	// Inclusive upper bound on the integer value space.
	MaximumValue *int `json:"maximum_value,omitempty"`
	// Footnote indicators attached to a datatype row.
	FootnoteNumbers []int `json:"footnote_numbers,omitempty"`
}

// A top-level business area of the FIX Latest specification.
type BusinessArea struct {
	// Identity of the business area.
	Area BusinessAreaEnum `json:"area"`
	// Display title of the area.
	Title *string `json:"title,omitempty"`
	// Description of the area.
	Description *string `json:"description,omitempty"`
	// Message categories defined within a business area.
	Categories []MessageCategory `json:"categories,omitempty"`
}

// A message category within a business area.
type MessageCategory struct {
	// Identity of the message category.
	Category MessageCategoryEnum `json:"category"`
	// Display title of the category.
	Title *string `json:"title,omitempty"`
	// Description of the category.
	Description *string `json:"description,omitempty"`
	// Business area the element belongs to.
	BusinessArea BusinessAreaEnum `json:"business_area"`
	// Messages defined within the enclosing element.
	Messages []Message `json:"messages,omitempty"`
}

// A FIX field — a uniquely tagged data element with a FIX datatype.
type Field struct {
	// Numeric tag of the field.
	Tag int `json:"tag"`
	// PascalCase name of the field.
	FieldName string `json:"field_name"`
	// FIX datatype of the field.
	Datatype FIXDatatypeName `json:"datatype"`
	// Description of the field's purpose.
	Description *string `json:"description,omitempty"`
	// Required-status of the field within the enclosing context.
	Requirement FieldRequirement `json:"requirement,omitempty"`
	// True when the field is a User Defined Field.
	IsUserDefined *bool `json:"is_user_defined,omitempty"`
}

// A FIX component — a named set of related fields.
type Component struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// Description of the component.
	Description *string `json:"description,omitempty"`
	// Sharing scope of the component.
	Scope ComponentScope `json:"scope"`
	// True when the component is a repeating group.
	IsRepeatingGroup *bool `json:"is_repeating_group,omitempty"`
	// Fields directly contained by the enclosing element.
	Fields []Field `json:"fields,omitempty"`
	// Components nested within this component.
	NestedComponents []ComponentId `json:"nested_components,omitempty"`
}

// A component shared by messages of two or more business areas.
type GlobalComponent struct {
	// Embedded types for inheritance
	Component `json:",inline"`
	// Thematic group under which the component is presented.
	ComponentGroup ComponentGroup `json:"component_group"`
	// Applicable at the Instrument level.
	AppliesToInstrument *bool `json:"applies_to_instrument,omitempty"`
	// Applicable at the InstrumentLeg level.
	AppliesToLeg *bool `json:"applies_to_leg,omitempty"`
	// Applicable at the UnderlyingInstrument level.
	AppliesToUnderlying *bool `json:"applies_to_underlying,omitempty"`
	// Names of other components conceptually identical to this one.
	ConceptuallyIdenticalTo []string `json:"conceptually_identical_to,omitempty"`
	// Numeric component identifier extracted from the FIX Latest "Global Components" page anchor ID (e.g. "comp1057-1" → 1057). Stable across Extension Packs and shared with the FIX Orchestra repository.
	GcId *int `json:"gc_id,omitempty"`
	// FIX business areas whose messages embed the Global Component.
	GcReferencedIn []GlobalComponentBusinessAreaEnum `json:"gc_referenced_in,omitempty"`
}

// A component used only by messages within a single business area.
type CommonComponent struct {
	// Embedded types for inheritance
	Component `json:",inline"`
	// Business area the element belongs to.
	BusinessArea BusinessAreaEnum `json:"business_area"`
}

// A component used only by messages within a single category.
type SpecificComponent struct {
	// Embedded types for inheritance
	Component `json:",inline"`
	// Business area the element belongs to.
	BusinessArea BusinessAreaEnum `json:"business_area"`
	// Message category.
	Category MessageCategoryEnum `json:"category"`
}

// A FIX application message.
type Message struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Description of the message's purpose.
	Description *string `json:"description,omitempty"`
	// Message category.
	Category MessageCategoryEnum `json:"category,omitempty"`
	// Fields directly contained by the enclosing element.
	Fields []Field `json:"fields,omitempty"`
	// Components referenced by the enclosing element.
	Components []ComponentId `json:"components,omitempty"`
}

// A reserved range of tag numbers for User Defined Fields.
type UDFTagRange struct {
	// Identifier of the range.
	RangeId string `json:"range_id"`
	// Inclusive lower bound of the range.
	LowTag int `json:"low_tag"`
	// Upper bound of the tag range. Required for all ``usage`` values except ``GTC_RESERVED`` (which is open-ended, 50000+). Downstream validators should enforce this; the constraint cannot be expressed here because LinkML's ``equals_string`` operator only accepts string-ranged slots and ``usage`` is an enum.
	HighTag *int `json:"high_tag,omitempty"`
	// Usage policy assigned to the range.
	Usage UDFTagRangeUsage `json:"usage"`
	// Notes on the range's intended use.
	Description *string `json:"description,omitempty"`
	// True when tags in the range must be registered.
	RequiresRegistration *bool `json:"requires_registration,omitempty"`
}

// Tree-root container for the Pre-Trade business area of FIX Latest.
type PreTradeBusinessArea struct {
	// Identity of the business area.
	Area BusinessAreaEnum `json:"area"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Version stamp from the document header.
	PublishedVersion *string `json:"published_version,omitempty"`
	// Publishing body of the FIX Latest specification.
	Publisher *string `json:"publisher,omitempty"`
	// Prose introduction of the chapter.
	Introduction *string `json:"introduction,omitempty"`
	// Sentence describing diagram conventions used in the chapter.
	DiagramConventions *string `json:"diagram_conventions,omitempty"`
	// Intro prose of the area-wide Messages sub-section.
	MessagesOverviewNote *string `json:"messages_overview_note,omitempty"`
	// Area-wide pre-trade messages table.
	Messages []PreTradeMessageEntry `json:"messages,omitempty"`
	// Intro prose of the area-wide Components sub-section.
	ComponentsOverviewNote *string `json:"components_overview_note,omitempty"`
	// Area-wide pre-trade components table.
	Components []PreTradeComponentEntry `json:"components,omitempty"`
	// Common Components declared at the top of the chapter.
	CommonComponents []PreTradeCommonComponentName `json:"common_components,omitempty"`
	// Per-common-component descriptions from the chapter's final section.
	CommonComponentDetails []CommonComponentDetail `json:"common_component_details,omitempty"`
	// Footnotes attached to the area-wide components table.
	Footnotes []ComponentTableFootnote `json:"footnotes,omitempty"`
	// Per-category sub-sections of the chapter.
	CategorySections []PreTradeCategorySection `json:"category_sections,omitempty"`
	// Names of Global Components from the FIX Latest "Global Components" page that are referenced by messages in the containing business area. References instances of the :class:`GlobalComponent` class (declared in fix_base) by name.
	ReferencedGlobalComponents []GlobalComponentId `json:"referenced_global_components,omitempty"`
}

// One row of the area-wide pre-trade messages table.
type PreTradeMessageEntry struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Message category.
	Category PreTradeCategoryEnum `json:"category"`
}

// One row of the area-wide pre-trade components table.
type PreTradeComponentEntry struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition"`
	// Category the component is listed under. Common Components are listed under the synthetic "Common Components" value.
	Category string `json:"category"`
	// True when the component is declared as a Common Component.
	IsCommon *bool `json:"is_common,omitempty"`
	// Footnote indicator on a component-table row.
	FootnoteNumber *int `json:"footnote_number,omitempty"`
}

// A footnote on the area-wide components table.
type ComponentTableFootnote struct {
	// Footnote indicator on a component-table row.
	FootnoteNumber int `json:"footnote_number"`
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// FIX version or Extension Pack that introduced the component.
	IntroducedIn string `json:"introduced_in"`
	// Single category that actually uses the component.
	SoleCategory PreTradeCategoryEnum `json:"sole_category"`
	// Footnote text.
	Text *string `json:"text,omitempty"`
}

// A per-category sub-section of the Pre-Trade chapter.
type PreTradeCategorySection struct {
	// Message category.
	Category PreTradeCategoryEnum `json:"category"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Quoting business models referenced in the Quotation / Negotiation category.
	QuoteModels []QuoteModelEnum `json:"quote_models,omitempty"`
	// Purpose-grouped message descriptions inside a category.
	MessageGroups []MessageGroup `json:"message_groups,omitempty"`
	// Messages defined in this category.
	Messages []PreTradeMessageDetail `json:"messages,omitempty"`
	// Intro prose of a category's Components sub-section.
	CategoryComponentsNote *string `json:"category_components_note,omitempty"`
	// Components used exclusively by messages within a category.
	CategorySpecificComponents []PreTradeComponentDetail `json:"category_specific_components,omitempty"`
}

// Per-category message description.
type PreTradeMessageDetail struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Description of the message's purpose and usage.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Pre-Trade Appendix.
	PreLayoutRows []PreTradeLayoutRow `json:"pre_layout_rows,omitempty"`
}

// Per-category component description.
type PreTradeComponentDetail struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition,omitempty"`
	// Description of the component's purpose.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Pre-Trade Appendix.
	PreLayoutRows []PreTradeLayoutRow `json:"pre_layout_rows,omitempty"`
}

// Purpose-grouped sub-section inside a category's Messages section.
type MessageGroup struct {
	// Purpose-group heading inside a category's Messages sub-section.
	GroupTitle string `json:"group_title"`
	// Description of the purpose-group's role within the category.
	Description *string `json:"description,omitempty"`
	// Messages bundled under the purpose-group heading.
	Messages []PreTradeMessageDetail `json:"messages"`
}

// Per-common-component description.
type CommonComponentDetail struct {
	// PascalCase name of the component.
	ComponentName PreTradeCommonComponentName `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition,omitempty"`
	// Description of the common component's purpose.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Pre-Trade Appendix.
	PreLayoutRows []PreTradeLayoutRow `json:"pre_layout_rows,omitempty"`
}

// One row of the layout table published in the Pre-Trade Appendix for a message or component. Each row identifies either a FIX field (by tag number + name) or an embedded component (by name), records whether it is required, carries the Description-column text, and flags whether it appears as a nested child of a repeating-group counter.
type PreTradeLayoutRow struct {
	// Row kind — either a FIX field (numeric Tag) or an embedded component (literal "Component" in the Tag column of the source table).
	PreLayoutKind PreTradeLayoutRowKindEnum `json:"pre_layout_kind"`
	// FIX tag number drawn from the Tag column when the row is a field (i.e. layout_kind = FIELD). Absent for COMPONENT rows.
	PreLayoutFieldTag *int `json:"pre_layout_field_tag,omitempty"`
	// Element name as printed in the Name column — either the FIX field name or the component name.
	PreLayoutElementName string `json:"pre_layout_element_name"`
	// Whether the field or component is required, as printed in the Req’d column of the source layout table ("Y" / "N").
	PreLayoutRequired *bool `json:"pre_layout_required,omitempty"`
	// Free-text content of the Description column of the row (may be empty).
	PreLayoutDescription *string `json:"pre_layout_description,omitempty"`
	// Whether the row appears nested under a repeating-group counter (i.e. its Tag column is prefixed with the "→" arrow in the source table).
	PreLayoutNested *bool `json:"pre_layout_nested,omitempty"`
}

// Tree-root container for the Trade (Orders and Executions) business area of FIX Latest.
type TradeBusinessArea struct {
	// Identity of the business area the chapter describes.
	TradeArea BusinessAreaEnum `json:"trade_area"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Version stamp from the document header.
	PublishedVersion *string `json:"published_version,omitempty"`
	// Publishing body of the FIX Latest specification.
	Publisher *string `json:"publisher,omitempty"`
	// Prose introduction of the chapter.
	TradeIntroduction *string `json:"trade_introduction,omitempty"`
	// Sentence describing diagram conventions used in the chapter.
	TradeDiagramConventions *string `json:"trade_diagram_conventions,omitempty"`
	// URL of the "Message Diagram Templates" page referenced by the chapter introduction.
	TradeMessageDiagramTemplateUrl *string `json:"trade_message_diagram_template_url,omitempty"`
	// Intro prose of the area-wide Messages sub-section.
	TradeMessagesOverviewNote *string `json:"trade_messages_overview_note,omitempty"`
	// Area-wide trade messages table.
	Messages []TradeMessageEntry `json:"messages,omitempty"`
	// Intro prose of the area-wide Components sub-section.
	TradeComponentsOverviewNote *string `json:"trade_components_overview_note,omitempty"`
	// Area-wide trade components table.
	Components []TradeComponentEntry `json:"components,omitempty"`
	// Common Components declared at the bottom of the chapter.
	TradeCommonComponents []TradeCommonComponentName `json:"trade_common_components,omitempty"`
	// Per-common-component descriptions from the chapter's final section.
	TradeCommonComponentDetails []TradeCommonComponentDetail `json:"trade_common_component_details,omitempty"`
	// Footnotes attached to the area-wide components table.
	TradeFootnotes []TradeComponentTableFootnote `json:"trade_footnotes,omitempty"`
	// Per-category sub-sections of the chapter.
	TradeCategorySections []TradeCategorySection `json:"trade_category_sections,omitempty"`
	// Names of Global Components from the FIX Latest "Global Components" page that are referenced by messages in the containing business area. References instances of the :class:`GlobalComponent` class (declared in fix_base) by name.
	ReferencedGlobalComponents []GlobalComponentId `json:"referenced_global_components,omitempty"`
}

// One row of the area-wide trade messages table.
type TradeMessageEntry struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Message category.
	Category TradeCategoryEnum `json:"category"`
}

// One row of the area-wide trade components table.
type TradeComponentEntry struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	TradeRepetition TradeComponentRepetition `json:"trade_repetition"`
	// Category the component is listed under. Common Components are listed under the synthetic "Common Components" value.
	Category string `json:"category"`
	// True when the component is declared as a Common Component.
	TradeIsCommon *bool `json:"trade_is_common,omitempty"`
	// Footnote indicator on a component-table row.
	TradeFootnoteNumber *int `json:"trade_footnote_number,omitempty"`
}

// A footnote on the area-wide components table.
type TradeComponentTableFootnote struct {
	// Footnote indicator on a component-table row.
	TradeFootnoteNumber int `json:"trade_footnote_number"`
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// FIX version or Extension Pack that introduced the component.
	TradeIntroducedIn string `json:"trade_introduced_in"`
	// Single category that actually uses the component.
	TradeSoleCategory TradeCategoryEnum `json:"trade_sole_category"`
	// Footnote text.
	TradeFootnoteText *string `json:"trade_footnote_text,omitempty"`
}

// A per-category sub-section of the Trade chapter.
type TradeCategorySection struct {
	// Message category.
	Category TradeCategoryEnum `json:"category"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Optional "Background" prose preceding a category's message descriptions (e.g. the Cross Order Handling chapter's cross-trade overview).
	TradeCategoryBackground *string `json:"trade_category_background,omitempty"`
	// Purpose-grouped message descriptions inside a category.
	TradeMessageGroups []TradeMessageGroup `json:"trade_message_groups,omitempty"`
	// Messages defined in this category.
	Messages []TradeMessageDetail `json:"messages,omitempty"`
	// Intro prose of a category's Components sub-section.
	TradeCategoryComponentsNote *string `json:"trade_category_components_note,omitempty"`
	// Components used exclusively by messages within a single category.
	TradeCategorySpecificComponents []TradeComponentDetail `json:"trade_category_specific_components,omitempty"`
	// Rows of the fragmentation table listed in a Trade category that documents which messages may be fragmented and which repeating group is fragmentable (currently published only for List/Program/Basket Trading).
	TradeFragmentationEntries []TradeFragmentationEntry `json:"trade_fragmentation_entries,omitempty"`
}

// Per-category message description.
type TradeMessageDetail struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Description of the message's purpose and usage.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout in the Trade Appendix.
	TradeLayoutUrl *string `json:"trade_layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Trade Appendix.
	TradeLayoutRows []TradeLayoutRow `json:"trade_layout_rows,omitempty"`
}

// Per-category component description.
type TradeComponentDetail struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	TradeRepetition TradeComponentRepetition `json:"trade_repetition,omitempty"`
	// Description of the component's purpose.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout in the Trade Appendix.
	TradeLayoutUrl *string `json:"trade_layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Trade Appendix.
	TradeLayoutRows []TradeLayoutRow `json:"trade_layout_rows,omitempty"`
}

// Purpose-grouped sub-section inside a category's Messages sub-section (e.g. "New Order Single", "Execution Reports", "Order Cancel Requests" under Single/General Order Handling).
type TradeMessageGroup struct {
	// Purpose-group heading inside a category's Messages sub-section.
	TradeGroupTitle string `json:"trade_group_title"`
	// Description of the purpose-group's role within the category.
	Description *string `json:"description,omitempty"`
	// Messages bundled under the purpose-group heading.
	Messages []TradeMessageDetail `json:"messages"`
	// Rows of the OrdStatus(39) precedence table that appears inside the Execution Reports purpose-group of the Single/General Order Handling category.
	TradeOrdStatusPrecedenceEntries []TradeOrdStatusPrecedenceEntry `json:"trade_ord_status_precedence_entries,omitempty"`
}

// Per-common-component description from the chapter's final "Common Components" section.
type TradeCommonComponentDetail struct {
	// PascalCase name of the component.
	ComponentName TradeCommonComponentName `json:"component_name"`
	// REPEATING or NON_REPEATING.
	TradeRepetition TradeComponentRepetition `json:"trade_repetition,omitempty"`
	// Description of the common component's purpose.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout in the Trade Appendix.
	TradeLayoutUrl *string `json:"trade_layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Trade Appendix.
	TradeLayoutRows []TradeLayoutRow `json:"trade_layout_rows,omitempty"`
}

// One row of the layout table published in the Trade Appendix for a message or component. Each row identifies either a FIX field (by tag number + name) or an embedded component (by name), records whether it is required, carries the Description-column text, and flags whether it appears as a nested child of a repeating-group counter.
type TradeLayoutRow struct {
	// Row kind — either a FIX field (numeric Tag) or an embedded component (literal "Component" in the Tag column of the source table).
	TradeLayoutKind TradeLayoutRowKindEnum `json:"trade_layout_kind"`
	// FIX tag number drawn from the Tag column when the row is a field (i.e. layout_kind = FIELD). Absent for COMPONENT rows.
	TradeLayoutFieldTag *int `json:"trade_layout_field_tag,omitempty"`
	// Element name as printed in the Name column — either the FIX field name or the component name.
	TradeLayoutElementName string `json:"trade_layout_element_name"`
	// Whether the field or component is required, as printed in the Req'd column of the source layout table ("Y" / "N").
	TradeLayoutRequired *bool `json:"trade_layout_required,omitempty"`
	// Free-text content of the Description column of the row (may be empty).
	TradeLayoutDescription *string `json:"trade_layout_description,omitempty"`
	// Whether the row appears nested under a repeating-group counter (i.e. its Tag column is prefixed with the "→" arrow in the source table).
	TradeLayoutNested *bool `json:"trade_layout_nested,omitempty"`
}

// One row of the OrdStatus(39) precedence table published in the Execution Reports purpose-group of the Single/General Order Handling category. Defines the precedence ranking used to resolve simultaneous state transitions on an order, paired with the human-readable OrdStatus label and its descriptive prose.
type TradeOrdStatusPrecedenceEntry struct {
	// Precedence rank (1 = lowest, higher numbers take precedence) of an OrdStatus(39) value used to resolve simultaneous state transitions on an order.
	TradeOrdStatusPrecedence int `json:"trade_ord_status_precedence"`
	// Human-readable OrdStatus(39) label as printed in the Execution Reports precedence table (e.g. "Pending Cancel", "Done for Day", "Filled").
	TradeOrdStatusLabel string `json:"trade_ord_status_label"`
	// Verbatim OrdStatus description from the table.
	Description *string `json:"description,omitempty"`
}

// One row of a fragmentation table published in a Trade category (currently only List/Program/Basket Trading) identifying a message that may be fragmented, the "Total Entries" field used to indicate the total count across all fragments of the batch, and the verbatim description of the repeating group that may be fragmented.
type TradeFragmentationEntry struct {
	// Message that may be fragmented — verbatim text from the Message column of the fragmentation table (e.g. "NewOrderList(35=E)").
	TradeFragmentationMessage string `json:"trade_fragmentation_message"`
	// Name and tag of the "Total Entries" field used to indicate the total count across all fragments of the batch (e.g. "TotNoOrders(68)").
	TradeFragmentationTotalEntriesField string `json:"trade_fragmentation_total_entries_field"`
	// Verbatim description of the repeating group that may be fragmented — from the table's third column.
	TradeFragmentationRepeatingGroup string `json:"trade_fragmentation_repeating_group"`
}

// Tree-root container for the Trade Appendix — the spec companion document that publishes the full message- and component-layout tables for every message and component used in the Trade business area, organized into one "Appendix – <X> Category" sub-section per Trade category plus a final "Appendix – Common Category" sub-section covering the layouts of the chapter's common components.
type TradeAppendix struct {
	// Display title.
	Title *string `json:"title,omitempty"`
	// Version stamp from the document header.
	PublishedVersion *string `json:"published_version,omitempty"`
	// Publishing body of the FIX Latest specification.
	Publisher *string `json:"publisher,omitempty"`
	// Optional preface prose for the Trade Appendix as a whole.
	Description *string `json:"description,omitempty"`
	// Per-category sub-sections of the Trade Appendix — one "Appendix – <X> Category" section per Trade category, plus a synthetic "Common Category" section that lists layouts of the chapter's common components.
	TradeAppendixSections []TradeAppendixSection `json:"trade_appendix_sections,omitempty"`
}

// One "Appendix – <X> Category" sub-section of the Trade Appendix. Bundles the per-message layout tables (TradeMessageDetail) and per-component layout tables (TradeComponentDetail) for messages and components that belong to one Trade category — or, for the synthetic "Common" section, the layouts of the chapter's common components.
type TradeAppendixSection struct {
	// Identifier for an appendix section — either the Trade category name as printed in the heading (e.g. "CrossOrders", "MultilegOrders", "OrderMassHandling", "ProgramTrading", "SingleGeneralOrderHandling") or the literal "Common" for the common-components appendix.
	TradeAppendixCategory string `json:"trade_appendix_category"`
	// Section heading exactly as printed in the Trade Appendix (e.g. "Appendix – CrossOrders Category").
	Title *string `json:"title,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Layout tables for the messages that belong to the appendix section. Empty for the "Common" section.
	Messages []TradeMessageDetail `json:"messages,omitempty"`
	// Layout tables for the components that belong to the appendix section.
	Components []TradeComponentDetailId `json:"components,omitempty"`
}

// Tree-root container for the Post-Trade business area of FIX Latest.
type PostTradeBusinessArea struct {
	// Identity of the business area.
	Area BusinessAreaEnum `json:"area"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Version stamp from the document header.
	PublishedVersion *string `json:"published_version,omitempty"`
	// Publishing body of the FIX Latest specification.
	Publisher *string `json:"publisher,omitempty"`
	// Prose introduction of the Post-Trade chapter.
	PostIntroduction *string `json:"post_introduction,omitempty"`
	// Sentence describing diagram conventions used in the chapter.
	DiagramConventions *string `json:"diagram_conventions,omitempty"`
	// Common Components declared at the top of the Post-Trade chapter.
	PostCommonComponents []PostTradeCommonComponentName `json:"post_common_components,omitempty"`
	// Messages defined within the enclosing element.
	Messages []PostTradeMessageEntry `json:"messages"`
	// Components referenced by the enclosing element.
	Components []PostTradeComponentEntry `json:"components"`
	// Footnotes attached to the area-wide components table.
	PostFootnotes []PostTradeComponentTableFootnote `json:"post_footnotes,omitempty"`
	// Per-category sub-sections of the Post-Trade chapter.
	PostCategorySections []PostTradeCategorySection `json:"post_category_sections,omitempty"`
	// Per-common-component descriptions from the chapter's final Common Components section.
	PostCommonComponentDetails []PostTradeCommonComponentDetail `json:"post_common_component_details,omitempty"`
	// Intro prose of the area-wide Messages sub-section.
	MessagesOverviewNote *string `json:"messages_overview_note,omitempty"`
	// Intro prose of the area-wide Components sub-section.
	ComponentsOverviewNote *string `json:"components_overview_note,omitempty"`
	// Names of Global Components from the FIX Latest "Global Components" page that are referenced by messages in the containing business area. References instances of the :class:`GlobalComponent` class (declared in fix_base) by name.
	ReferencedGlobalComponents []GlobalComponentId `json:"referenced_global_components,omitempty"`
}

// One row of the area-wide "Messages for Post-Trade Business Area" table.
type PostTradeMessageEntry struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Message category.
	Category PostTradeCategoryEnum `json:"category"`
}

// One row of the area-wide "Components for Post-Trade Business Area" table.
type PostTradeComponentEntry struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition"`
	// Category label as printed in the component table; the token "Common Components" is allowed in addition to the PostTradeCategoryEnum values.
	Category string `json:"category"`
	// True when the component is declared as a Common Component.
	IsCommon *bool `json:"is_common,omitempty"`
	// Footnote indicator on a component-table row.
	FootnoteNumber *int `json:"footnote_number,omitempty"`
}

// A footnote attached to a row of the area-wide Post-Trade components table.
type PostTradeComponentTableFootnote struct {
	// Footnote indicator on a component-table row.
	FootnoteNumber int `json:"footnote_number"`
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// FIX version or Extension Pack that introduced the component.
	IntroducedIn string `json:"introduced_in"`
	// Single Post-Trade category that actually uses the component (per footnote).
	PostSoleCategory PostTradeCategoryEnum `json:"post_sole_category"`
	// Footnote text.
	Text *string `json:"text,omitempty"`
}

// A "Category – <name>" sub-section of the Post-Trade chapter.
type PostTradeCategorySection struct {
	// Message category.
	Category PostTradeCategoryEnum `json:"category"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Intro prose of a category's Components sub-section.
	CategoryComponentsNote *string `json:"category_components_note,omitempty"`
	// Purpose-grouped message descriptions inside a Post-Trade category.
	PostMessageGroups []PostTradeMessageGroup `json:"post_message_groups,omitempty"`
	// Messages defined within the enclosing element.
	Messages []PostTradeMessageDetail `json:"messages,omitempty"`
	// Components used exclusively by messages within a category.
	PostCategorySpecificComponents []PostTradeComponentDetail `json:"post_category_specific_components,omitempty"`
	// Communication options supported by the Allocation category for conveying allocation instructions.
	AllocationScenarios []AllocationScenarioEnum `json:"allocation_scenarios,omitempty"`
	// Role labels used throughout the Allocation category prose.
	AllocationRoles []AllocationRoleEnum `json:"allocation_roles,omitempty"`
	// Methods supported for computing post-trade allocations.
	PostTradeAllocationPricingMethods []PostTradeAllocationPricingMethodEnum `json:"post_trade_allocation_pricing_methods,omitempty"`
	// Descriptions tied to AllocStatus(87) values as listed in the Allocation Instruction Acknowledgements section.
	AllocationStatusDescriptions []AllocationStatusDescription `json:"allocation_status_descriptions,omitempty"`
	// Per-message mapping of fragmentation-related fields used by the Allocation messages.
	FragmentationFieldMap []AllocationFragmentationFieldMap `json:"fragmentation_field_map,omitempty"`
	// Usages described in the "Trade Capture Report Usages" sub-section of the Trade Capture Reporting category.
	TradeCaptureReportUsages []TradeCaptureReportUsage `json:"trade_capture_report_usages,omitempty"`
	// Rules governing TradeCaptureReport(35=AE) identifier fields.
	TradeCaptureReportIdentifierRules []TradeCaptureReportIdentifierRule `json:"trade_capture_report_identifier_rules,omitempty"`
	// Descriptions tied to RegistStatus(506) values.
	RegistrationStatusDescriptions []RegistrationStatusDescription `json:"registration_status_descriptions,omitempty"`
	// Business functions exposed by the Position Management Clearing Services.
	ClearingServicesForPositionManagement []ClearingServiceForPositionManagementEnum `json:"clearing_services_for_position_management,omitempty"`
	// Per-format action sets exposed by the Post-Trade Processing Clearing Services.
	ClearingServicesForPostTradeProcessing []ClearingServicePostTradeProcessingFormat `json:"clearing_services_for_post_trade_processing,omitempty"`
	// Documented usages for the Collateral Management messages.
	CollateralManagementUsages []CollateralManagementUsageEnum `json:"collateral_management_usages,omitempty"`
	// Documented purposes for the CollateralAssignment(35=AY) message.
	CollateralAssignmentPurposes []CollateralAssignmentPurposeEnum `json:"collateral_assignment_purposes,omitempty"`
}

// A purpose-themed grouping of messages within a Post-Trade category (e.g. "Allocation Instructions").
type PostTradeMessageGroup struct {
	// Purpose-group heading inside a category's Messages sub-section.
	GroupTitle string `json:"group_title"`
	// Messages defined within the enclosing element.
	Messages []PostTradeMessageDetail `json:"messages"`
}

// Per-message description block from a Post-Trade category section.
type PostTradeMessageDetail struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Post-Trade Appendix.
	PostLayoutRows []PostTradeLayoutRow `json:"post_layout_rows,omitempty"`
}

// Per-component description block from a Post-Trade category section's Components sub-section.
type PostTradeComponentDetail struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Post-Trade Appendix.
	PostLayoutRows []PostTradeLayoutRow `json:"post_layout_rows,omitempty"`
}

// Per-common-component description block from the chapter's final "Common Components" section.
type PostTradeCommonComponentDetail struct {
	// PascalCase name of the component.
	ComponentName PostTradeCommonComponentName `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Post-Trade Appendix.
	PostLayoutRows []PostTradeLayoutRow `json:"post_layout_rows,omitempty"`
}

// One row of the AllocStatus(87) value/description table.
type AllocationStatusDescription struct {
	// Wire status code as referenced in the chapter.
	StatusCode string `json:"status_code"`
	// Human-readable label of the status code.
	StatusLabel string `json:"status_label"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
}

// One row of the table mapping an allocation message to its fragmentation-related fields.
type AllocationFragmentationFieldMap struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Field carrying the total number of repeating-group entries across all fragments (e.g. TotNoAllocs).
	TotalCountField string `json:"total_count_field"`
	// Field carrying the number of entries in the current message fragment (e.g. NoAllocs).
	FragmentCountField string `json:"fragment_count_field"`
	// Principal message reference field used to bind allocation message fragments together (e.g. AllocID, AllocReportID).
	PrincipalMessageReference string `json:"principal_message_reference"`
}

// One documented usage of the TradeCaptureReport(35=AE) message.
type TradeCaptureReportUsage struct {
	// Short label for the usage.
	StatusLabel string `json:"status_label"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Role of the trade-capture-report identifier field.
	IdentifierRole TradeCaptureReportIdentifierRoleEnum `json:"identifier_role,omitempty"`
}

// A rule governing one of the TradeCaptureReport(35=AE) identifier fields.
type TradeCaptureReportIdentifierRule struct {
	// Role of the trade-capture-report identifier field.
	IdentifierRole TradeCaptureReportIdentifierRoleEnum `json:"identifier_role"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
}

// One row of the RegistStatus(506) value/description table.
type RegistrationStatusDescription struct {
	// Wire status code as referenced in the chapter.
	StatusCode string `json:"status_code"`
	// Human-readable label of the status code.
	StatusLabel string `json:"status_label"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
}

// One message-format row from the Post-Trade Processing Clearing Services section, with its supported actions.
type ClearingServicePostTradeProcessingFormat struct {
	// Clearing-service message format family referenced in the chapter.
	MessageFormat ClearingServiceForPostTradeProcessingEnum `json:"message_format"`
	// Action labels (e.g. Allocation, Accept, Reject, Release, Change, Delete) supported by a clearing-service message format.
	SupportedActions []string `json:"supported_actions"`
}

// One row of the layout table published in the Post-Trade Appendix for a message or component. Each row identifies either a FIX field (by tag number + name) or an embedded component (by name), records whether it is required, carries the Description-column text, and flags whether it appears as a nested child of a repeating-group counter.
type PostTradeLayoutRow struct {
	// Row kind — either a FIX field (numeric Tag) or an embedded component (literal "Component" in the Tag column of the source table).
	PostLayoutKind PostTradeLayoutRowKindEnum `json:"post_layout_kind"`
	// FIX tag number drawn from the Tag column when the row is a field (i.e. layout_kind = FIELD). Absent for COMPONENT rows.
	PostLayoutFieldTag *int `json:"post_layout_field_tag,omitempty"`
	// Element name as printed in the Name column — either the FIX field name or the component name.
	PostLayoutElementName string `json:"post_layout_element_name"`
	// Whether the field or component is required, as printed in the Req’d column of the source layout table ("Y" / "N").
	PostLayoutRequired *bool `json:"post_layout_required,omitempty"`
	// Free-text content of the Description column of the row (may be empty).
	PostLayoutDescription *string `json:"post_layout_description,omitempty"`
	// Whether the row appears nested under a repeating-group counter (i.e. its Tag column is prefixed with the "→" arrow in the source table).
	PostLayoutNested *bool `json:"post_layout_nested,omitempty"`
}

// Tree-root container for the Infrastructure business area of FIX Latest.
type InfrastructureBusinessArea struct {
	// Identity of the business area.
	Area BusinessAreaEnum `json:"area"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Version stamp from the document header.
	PublishedVersion *string `json:"published_version,omitempty"`
	// Publishing body of the FIX Latest specification.
	Publisher *string `json:"publisher,omitempty"`
	// Prose introduction of the Infrastructure chapter.
	InfraIntroduction *string `json:"infra_introduction,omitempty"`
	// Sentence describing diagram conventions used in the chapter.
	DiagramConventions *string `json:"diagram_conventions,omitempty"`
	// Component names declared in the area-wide components listing. Per the chapter prose, none of these are shared across categories within the area.
	InfraCommonComponents []InfrastructureComponentName `json:"infra_common_components,omitempty"`
	// Messages defined within the enclosing element.
	Messages []InfrastructureMessageEntry `json:"messages"`
	// Intro prose of the area-wide Messages sub-section.
	MessagesOverviewNote *string `json:"messages_overview_note,omitempty"`
	// Components referenced by the enclosing element.
	Components []InfrastructureComponentEntry `json:"components"`
	// Intro prose of the area-wide Components sub-section.
	ComponentsOverviewNote *string `json:"components_overview_note,omitempty"`
	// Footnotes attached to the area-wide Infrastructure components table.
	InfraFootnotes []InfrastructureComponentTableFootnote `json:"infra_footnotes,omitempty"`
	// Per-category sub-sections of the Infrastructure chapter.
	InfraCategorySections []InfrastructureCategorySection `json:"infra_category_sections,omitempty"`
	// "Standard Responses for Pre-Trade Messages" table rows.
	StandardResponsesPreTrade []StandardResponseMapping `json:"standard_responses_pre_trade,omitempty"`
	// "Standard Responses for Trade Messages" table rows.
	StandardResponsesTrade []StandardResponseMapping `json:"standard_responses_trade,omitempty"`
	// "Standard Responses for Post-Trade Messages" table rows.
	StandardResponsesPostTrade []StandardResponseMapping `json:"standard_responses_post_trade,omitempty"`
	// "Key Fields for Pre-Trade Application Message References" table rows.
	KeyFieldsPreTrade []ApplicationMessageReferenceKey `json:"key_fields_pre_trade,omitempty"`
	// "Key Fields for Trade Application Message References" table rows.
	KeyFieldsTrade []ApplicationMessageReferenceKey `json:"key_fields_trade,omitempty"`
	// "Key Fields for Post-Trade Application Message References" table rows.
	KeyFieldsPostTrade []ApplicationMessageReferenceKey `json:"key_fields_post_trade,omitempty"`
	// Descriptions tied to BusinessRejectReason(380) values.
	BusinessRejectReasonDescriptions []BusinessRejectReasonDescription `json:"business_reject_reason_descriptions,omitempty"`
	// Global Components (from the FIX Latest "Global Components" page) that are explicitly referenced by messages in the Infrastructure business area, together with their tag set and usage scope.
	InfraGlobalComponents []InfrastructureGlobalComponentReference `json:"infra_global_components,omitempty"`
	// Names of Global Components from the FIX Latest "Global Components" page that are referenced by messages in the containing business area. References instances of the :class:`GlobalComponent` class (declared in fix_base) by name.
	ReferencedGlobalComponents []GlobalComponentId `json:"referenced_global_components,omitempty"`
}

// One row of the area-wide "Messages for Infrastructure Business Area" table.
type InfrastructureMessageEntry struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Message category.
	Category InfrastructureCategoryEnum `json:"category"`
}

// One row of the area-wide "Components for Infrastructure Business Area" table.
type InfrastructureComponentEntry struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition"`
	// Message category.
	Category InfrastructureCategoryEnum `json:"category"`
	// Footnote indicator on a component-table row.
	FootnoteNumber *int `json:"footnote_number,omitempty"`
}

// A footnote attached to a row of the area-wide Infrastructure components table.
type InfrastructureComponentTableFootnote struct {
	// Footnote indicator on a component-table row.
	FootnoteNumber int `json:"footnote_number"`
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// FIX version or Extension Pack that introduced the component.
	IntroducedIn string `json:"introduced_in"`
	// Single Infrastructure category that actually uses the footnoted component.
	InfraSoleCategory InfrastructureCategoryEnum `json:"infra_sole_category"`
	// Footnote text.
	Text *string `json:"text,omitempty"`
}

// A "Category – <name>" sub-section of the Infrastructure chapter.
type InfrastructureCategorySection struct {
	// Message category.
	Category InfrastructureCategoryEnum `json:"category"`
	// Display title.
	Title *string `json:"title,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// Intro prose of a category's Components sub-section.
	CategoryComponentsNote *string `json:"category_components_note,omitempty"`
	// Messages defined within the enclosing element.
	Messages []InfrastructureMessageDetail `json:"messages,omitempty"`
	// Per-component descriptions appearing in a category's Components sub-section.
	InfraCategorySpecificComponents []InfrastructureComponentDetail `json:"infra_category_specific_components,omitempty"`
	// Network Status Communication usage scenarios.
	NetworkStatusScenarios []NetworkStatusScenarioEnum `json:"network_status_scenarios,omitempty"`
	// NetworkRequestType(935) values explicitly cited in the Network Status Communication category prose.
	NetworkRequestTypesReferenced []NetworkRequestTypeEnum `json:"network_request_types_referenced,omitempty"`
	// Documented uses of ApplicationMessageReport(35=BY).
	ApplicationMessageReportUses []ApplicationMessageReportTypeEnum `json:"application_message_report_uses,omitempty"`
}

// Per-message description appearing in a category's Messages sub-section.
type InfrastructureMessageDetail struct {
	// MsgType(35) wire value identifying the message.
	MsgType string `json:"msg_type"`
	// PascalCase name of the message.
	MessageName string `json:"message_name"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Infrastructure Appendix.
	InfraLayoutRows []InfrastructureLayoutRow `json:"infra_layout_rows,omitempty"`
}

// Per-component description appearing in a category's Components sub-section.
type InfrastructureComponentDetail struct {
	// PascalCase name of the component.
	ComponentName string `json:"component_name"`
	// REPEATING or NON_REPEATING.
	Repetition ComponentRepetition `json:"repetition,omitempty"`
	// Free-text description.
	Description *string `json:"description,omitempty"`
	// URL of the detailed message- or component-layout.
	LayoutUrl *string `json:"layout_url,omitempty"`
	// Ordered rows of the layout table published for the message or component in the Infrastructure Appendix.
	InfraLayoutRows []InfrastructureLayoutRow `json:"infra_layout_rows,omitempty"`
}

// One row of the layout table published in the Infrastructure Appendix for a message or component. Each row identifies either a FIX field (by tag number + name) or an embedded component (by name), records whether it is required, carries the Description-column text, and flags whether it appears as a nested child of a repeating-group counter.
type InfrastructureLayoutRow struct {
	// Row kind — either a FIX field (numeric Tag) or an embedded component (literal "Component" in the Tag column of the source table).
	InfraLayoutKind InfrastructureLayoutRowKindEnum `json:"infra_layout_kind"`
	// FIX tag number drawn from the Tag column when the row is a field (i.e. layout_kind = FIELD). Absent for COMPONENT rows.
	InfraLayoutFieldTag *int `json:"infra_layout_field_tag,omitempty"`
	// Element name as printed in the Name column — either the FIX field name (e.g. ApplReqID) or the component name (e.g. StandardHeader, ApplIDRequestGrp).
	InfraLayoutElementName string `json:"infra_layout_element_name"`
	// Whether the field or component is required, as printed in the Req’d column of the source layout table ("Y" / "N").
	InfraLayoutRequired *bool `json:"infra_layout_required,omitempty"`
	// Free-text content of the Description column of the row (may be empty).
	InfraLayoutDescription *string `json:"infra_layout_description,omitempty"`
	// Whether the row appears nested under a repeating-group counter (i.e. its Tag column is prefixed with the "→" arrow in the source table).
	InfraLayoutNested *bool `json:"infra_layout_nested,omitempty"`
}

// One row of a "Standard Responses for <area> Messages" table mapping a request message to its appropriate response(s).
type StandardResponseMapping struct {
	// Category label as printed in the source table (free text; may include parenthesised sub-categories such as "Single General Order Handling").
	CategoryLabel string `json:"category_label"`
	// FIX message name with MsgType in parentheses, e.g. AllocationInstruction(35=J).
	FixMessage string `json:"fix_message"`
	// Free-text appropriate-response cell from the Standard Responses tables.
	AppropriateResponses string `json:"appropriate_responses"`
}

// One row of a "Key Fields for <area> Application Message References" table identifying the field whose value is copied into BusinessRejectRefID(379).
type ApplicationMessageReferenceKey struct {
	// Category label as printed in the source table (free text; may include parenthesised sub-categories such as "Single General Order Handling").
	CategoryLabel string `json:"category_label"`
	// FIX message name with MsgType in parentheses, e.g. AllocationInstruction(35=J).
	FixMessage string `json:"fix_message"`
	// Source field copied into BusinessRejectRefID(379) when the target message lacks its own reject. May enumerate several alternatives joined by "or".
	BusinessRejectRefIdValue string `json:"business_reject_ref_id_value"`
}

// One entry of the BusinessRejectReason(380) code table.
type BusinessRejectReasonDescription struct {
	// Numeric code value of BusinessRejectReason(380).
	RejectReasonCode int `json:"reject_reason_code"`
	// Human-readable label of a BusinessRejectReason(380) code.
	RejectReasonLabel string `json:"reject_reason_label"`
}

// A reference from the Infrastructure business area to a Global Component declared on the FIX Latest "Global Components" page. Records the component name, the FIX tags it contributes, and the Infrastructure categories and messages that embed it.
type InfrastructureGlobalComponentReference struct {
	// Name of a Global Component referenced from within the Infrastructure business area.
	InfraGlobalComponentName InfrastructureGlobalComponentName `json:"infra_global_component_name"`
	// Repetition indicator for the Global Component as it appears in the referenced Infrastructure messages.
	InfraGlobalComponentRepetition *string `json:"infra_global_component_repetition,omitempty"`
	// FIX tag numbers contributed by the referenced Global Component (as listed on the Global Components page).
	InfraGlobalComponentFieldTags []int `json:"infra_global_component_field_tags,omitempty"`
	// Human-readable field names of the tags contributed by the referenced Global Component.
	InfraGlobalComponentFieldNames []string `json:"infra_global_component_field_names,omitempty"`
	// Infrastructure categories that reference the Global Component.
	InfraGlobalComponentUsedIn []InfrastructureCategoryEnum `json:"infra_global_component_used_in"`
	// MsgType values within the Infrastructure business area that embed the referenced Global Component.
	InfraGlobalComponentMsgTypes []string `json:"infra_global_component_msg_types,omitempty"`
}

type ComponentId string

type GlobalComponentId string

type TradeComponentDetailId string


